### ISSUE TITLE
Error while installing alkiranet/alkira v0.9.5: checksum list has no SHA-256 hash for "terraform-provider-alkira_0.9.5_windows_amd64.zip

### ISSUE THREAD

**Issue by mahesh2543** [alkiranet/terraform-provider-alkira#175]
@spikewang , @SpaSmALX @mac-alkira 
I am trying to do terraform init for alkira , but i am facing this error.

terraform {
  required_providers {
    alkira = {
      source = "alkiranet/alkira"
      version = "0.9.5"
    }
  }
}

provider "alkira" {
  portal   = "your_tenant_name.portal.alkira.com"
  username = "your_name@email.com"
  password = "your_password"
}

**Comment by mahesh2543** [comment]
@spikewang

**Comment by spikewang** [comment]
Hi @mahesh2543, this could be some intermittent issue of Terraform Registry. Could you try again and if it still doesn't work. you could paste the output of this command `TF_LOG=DEBUG terraform init` I will follow up with HashiCorp.

**Comment by spikewang** [comment]
Just tried on windows with Terraform 1.2.8. Seems like working fine to me.

**Comment by spikewang** [comment]
HI @mahesh2543, do you still have this issue?

**Comment by mahesh2543** [comment]
no @spikewang Thanks
