### ISSUE TITLE
alkira_connector_azure_vnet

### ISSUE THREAD

**Issue by AmudaPalani** [alkiranet/terraform-provider-alkira#251]
According to examples in https://registry.terraform.io/providers/alkiranet/alkira/latest/docs/resources/connector_azure_vnet, the credential_id is alkira_credential_azure_vnet.id, but in this sample repo, it's alkira_credential.id:
https://github.com/alkiranet/terraform-alkira-connector-azure/blob/main/main.tf#L37.

Please clarify whether it's alkira_credential_azure_vnet or alkira_credential?

**Comment by spikewang** [comment]
Hi @AmudaPalani I looked at the case, That's a data source example. It tried to refer to an existing credential already created outside of the config. If you are creating the credential in your config, it should be `alkira_credential_azure_vnet`. Which case you are trying to do?

**Comment by spikewang** [comment]
There are two, resource `alkira_credential_azure_vnet`, and there is data source as described here: https://registry.terraform.io/providers/alkiranet/alkira/latest/docs/data-sources/credential
