### ISSUE TITLE
alkira_connector_remote_access (Resource) doesn't accept prefixes.

### ISSUE THREAD

**Issue by mcomisso-elux** [alkiranet/terraform-provider-alkira#308]
Hi,
I'm using Terraform to deploy a remote_access resource following this documentation https://registry.terraform.io/providers/alkiranet/alkira/latest/docs/resources/connector_remote_access.

Seems that it is possible to enable split_tunneling but there is no option in the schema to set the prefix list.

**Comment by spikewang** [comment]
Yes, `prefix_list_id` should be there. Missed it from the initial implementation... Will have it in the next patch release!

**Comment by spikewang** [comment]
This is fixed now. Will plan a new release tomorrow. Thanks for the report!
